package strategy

import "git.x6c.co/go/blackjack/pkg/blackjack"

var Soft = StrategyTable{
	// Ace, two
	3: {
		blackjack.TwoName:   blackjack.Hit,
		blackjack.ThreeName: blackjack.Hit,
		blackjack.FourName:  blackjack.Hit,
		blackjack.FiveName:  blackjack.Hit,
		blackjack.SixName:   blackjack.Hit,
		blackjack.SevenName: blackjack.Hit,
		blackjack.EightName: blackjack.Hit,
		blackjack.NineName:  blackjack.Hit,
		blackjack.TenName:   blackjack.Hit,
		blackjack.JackName:  blackjack.Hit,
		blackjack.QueenName: blackjack.Hit,
		blackjack.KingName:  blackjack.Hit,
		blackjack.AceName:   blackjack.Hit,
	},
	// Ace, three
	4: {
		blackjack.TwoName:   blackjack.Hit,
		blackjack.ThreeName: blackjack.Hit,
		blackjack.FourName:  blackjack.Hit,
		blackjack.FiveName:  blackjack.Hit,
		blackjack.SixName:   blackjack.Hit,
		blackjack.SevenName: blackjack.Hit,
		blackjack.EightName: blackjack.Hit,
		blackjack.NineName:  blackjack.Hit,
		blackjack.TenName:   blackjack.Hit,
		blackjack.JackName:  blackjack.Hit,
		blackjack.QueenName: blackjack.Hit,
		blackjack.KingName:  blackjack.Hit,
		blackjack.AceName:   blackjack.Hit,
	},
	// Ace, four
	5: {
		blackjack.TwoName:   blackjack.Hit,
		blackjack.ThreeName: blackjack.Hit,
		blackjack.FourName:  blackjack.Hit,
		blackjack.FiveName:  blackjack.Hit,
		blackjack.SixName:   blackjack.Hit,
		blackjack.SevenName: blackjack.Hit,
		blackjack.EightName: blackjack.Hit,
		blackjack.NineName:  blackjack.Hit,
		blackjack.TenName:   blackjack.Hit,
		blackjack.JackName:  blackjack.Hit,
		blackjack.QueenName: blackjack.Hit,
		blackjack.KingName:  blackjack.Hit,
		blackjack.AceName:   blackjack.Hit,
	},
	// Ace, five
	6: {
		blackjack.TwoName:   blackjack.Hit,
		blackjack.ThreeName: blackjack.Hit,
		blackjack.FourName:  blackjack.Hit,
		blackjack.FiveName:  blackjack.Hit,
		blackjack.SixName:   blackjack.Hit,
		blackjack.SevenName: blackjack.Hit,
		blackjack.EightName: blackjack.Hit,
		blackjack.NineName:  blackjack.Hit,
		blackjack.TenName:   blackjack.Hit,
		blackjack.JackName:  blackjack.Hit,
		blackjack.QueenName: blackjack.Hit,
		blackjack.KingName:  blackjack.Hit,
		blackjack.AceName:   blackjack.Hit,
	},
	// Ace, six
	7: {
		blackjack.TwoName:   blackjack.Hit,
		blackjack.ThreeName: blackjack.Hit,
		blackjack.FourName:  blackjack.Hit,
		blackjack.FiveName:  blackjack.Hit,
		blackjack.SixName:   blackjack.Hit,
		blackjack.SevenName: blackjack.Hit,
		blackjack.EightName: blackjack.Hit,
		blackjack.NineName:  blackjack.Hit,
		blackjack.TenName:   blackjack.Hit,
		blackjack.JackName:  blackjack.Hit,
		blackjack.QueenName: blackjack.Hit,
		blackjack.KingName:  blackjack.Hit,
		blackjack.AceName:   blackjack.Hit,
	},
	// Ace, seven
	8: {
		blackjack.TwoName:   blackjack.Stand,
		blackjack.ThreeName: blackjack.Stand,
		blackjack.FourName:  blackjack.Stand,
		blackjack.FiveName:  blackjack.Stand,
		blackjack.SixName:   blackjack.Stand,
		blackjack.SevenName: blackjack.Stand,
		blackjack.EightName: blackjack.Stand,
		blackjack.NineName:  blackjack.Stand,
		blackjack.TenName:   blackjack.Stand,
		blackjack.JackName:  blackjack.Stand,
		blackjack.QueenName: blackjack.Hit,
		blackjack.KingName:  blackjack.Hit,
		blackjack.AceName:   blackjack.Hit,
	},
	// Ace, eight
	9: {
		blackjack.TwoName:   blackjack.Stand,
		blackjack.ThreeName: blackjack.Stand,
		blackjack.FourName:  blackjack.Stand,
		blackjack.FiveName:  blackjack.Stand,
		blackjack.SixName:   blackjack.Stand,
		blackjack.SevenName: blackjack.Stand,
		blackjack.EightName: blackjack.Stand,
		blackjack.NineName:  blackjack.Stand,
		blackjack.TenName:   blackjack.Stand,
		blackjack.JackName:  blackjack.Stand,
		blackjack.QueenName: blackjack.Stand,
		blackjack.KingName:  blackjack.Stand,
		blackjack.AceName:   blackjack.Stand,
	},
	// Ace, nine
	10: {
		blackjack.TwoName:   blackjack.Stand,
		blackjack.ThreeName: blackjack.Stand,
		blackjack.FourName:  blackjack.Stand,
		blackjack.FiveName:  blackjack.Stand,
		blackjack.SixName:   blackjack.Stand,
		blackjack.SevenName: blackjack.Stand,
		blackjack.EightName: blackjack.Stand,
		blackjack.NineName:  blackjack.Stand,
		blackjack.TenName:   blackjack.Stand,
		blackjack.JackName:  blackjack.Stand,
		blackjack.QueenName: blackjack.Stand,
		blackjack.KingName:  blackjack.Stand,
		blackjack.AceName:   blackjack.Stand,
	},
}
